apiVersion: v1
kind: Pod
metadata:
  name: privileged-escape-sim
  namespace: default
  labels:
    attack: "02-privileged-escape"
    mitre: "T1611"
spec:
  containers:
  - name: attacker
    image: alpine:3.18
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
